---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
        exclude: '^\.config/.*|^\.local/.*'
      - id: check-yaml
        exclude: '^\.local/share/.*'
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
        exclude: '^\.local/share/.*'
      - id: trailing-whitespace
        exclude: '^\.local/share/.*'

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        exclude: '^\.config/.*|^\.local/.*|^\.shellrc/zshrc\.d/.*|\.zsh(##.*)?$|^\.zlogin$|\.sh##default$'

  - repo: local
    hooks:
      - id: zsh-syntax-check
        name: zsh syntax check
        entry: zsh -n
        language: system
        files: '\.zsh(##.*)?$|^\.zlogin$|^\.shellrc/zshrc\.d/functions/[^/]+$'
        exclude: '^\.config/.*|^\.local/.*'

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint.yml"]
        exclude: '^\.config/.*|^\.local/.*'

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlintrc"]
        exclude: '^\.config/.*|^\.local/.*'

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.0.1
    hooks:
      - id: stylua
        args: ["--config-path", ".config/nvim/.stylua.toml"]
        exclude: '^\.config/.*|^\.local/.*'

  - repo: https://github.com/rubocop/rubocop
    rev: v1.69.2
    hooks:
      - id: rubocop
        exclude: '^\.config/.*|^\.local/.*'

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
      - id: editorconfig-checker
        exclude: '^\.config/.*|^\.local/.*|^\.shellrc/zshrc\.d/functions/scripts/.*\.rb$|\.md$'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [json, markdown, yaml]
        exclude: '^\.config/.*|^\.local/.*'
