[tools]
cargo-binstall = "latest"
glab = "latest"
golang = "1.25.6"
golangci-lint = "latest"
just = "latest"
pre-commit = "latest"
ruby = "3.4.8"
rust = "stable"
teleport-community = "17"

[settings]
idiomatic_version_file_enable_tools = []
