[settings]
node.mirror_url = "https://unofficial-builds.nodejs.org/download/release/"
node.flavor = "glibc-217"

[tools]
bat = "latest"
bottom = "latest"
cargo-binstall = "latest"
ctop = "latest"
delta = "latest"
dive = "latest"
duf = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
gitleaks = "latest"
golang = "latest"
hyperfine = "latest"
jless = "0.7.2"
jq = "latest"
just = "latest"
lazydocker = "latest"
lazygit = "latest"
nodejs = "23.7.0"
pre-commit = "latest"
ripgrep = "latest"
rust = { version = "stable", profile = "minimal", targets = "x86_64-unknown-linux-musl" }
shellcheck = "latest"
stylua = "latest"
viddy = "latest"
xh = "latest"
zoxide = "latest"
