[tools]
cargo-binstall = "latest"
dive = "latest"
fd = "latest"
glab = "latest"
golang = "1.25.5"
golangci-lint = "latest"
just = "latest"
nodejs = "25.2.1"
pre-commit = "latest"
ruby = "3.4.8"
rust = "stable"
yamllint = "latest"
teleport-community = "17"

[settings]
idiomatic_version_file_enable_tools = []
