[tools]
bat = "latest"
bottom = "latest"
cargo-binstall = "latest"
"cargo:tree-sitter-cli" = "0.25.9"
ctop = "latest"
delta = "latest"
dive = "latest"
duf = "latest"
dust = "latest"
fd = "latest"
github-cli = "latest"
gitleaks = "latest"
golang = "latest"
hyperfine = "latest"
jq = "latest"
just = "latest"
lazydocker = "latest"
lazygit = "latest"
pre-commit = "latest"
ripgrep = "latest"
shellcheck = "latest"
viddy = "latest"
xh = "latest"
